### ISSUE TITLE
Magically dissapearing harmonised nightmare staff

### ISSUE THREAD

**Issue by lostcokecan** [oldschoolgg/oldschoolbot#1052]
## 🐛 Bug Report
Pretty much what the title says, my harmonised nightnare staff dissapeared inbetween me joining a nightmare mass and it starting in the #nightmare-mass channel. I wanted to dismantle it in the #bot-channel so i went to unequip it using the "+unequip mage harmonised nightmare staff" command the image and text appeared showing it had been unequipped but when i went to do the "+create harmonised orb" command it told me the item was not to be found, i have searched the bank with other members of the community helping, i have had 'Fishy' assist me in trying to find it but we have been unsuccesful and directed to report the bug. I have attached some images but i couldnt get the earlier commands/comments due to the chat dissapearing with too many comments on mobile.
![Screenshot_20201128-194636_Discord](https://user-images.githubusercontent.com/75183023/100525390-6731ea00-31b8-11eb-8ec8-428b90f16c14.jpg)
![Screenshot_20201128-194940_Discord](https://user-images.githubusercontent.com/75183023/100525392-67ca8080-31b8-11eb-84c2-6632d28b0c4a.jpg)
![Screenshot_20201128-195536_Discord](https://user-images.githubusercontent.com/75183023/100525394-68631700-31b8-11eb-80ab-4f60d9ffb0ee.jpg)
![Screenshot_20201128-195516_Discord](https://user-images.githubusercontent.com/75183023/100525395-68fbad80-31b8-11eb-8c98-333da56d9d84.jpg)

Image #1 is me with the staff equipped from a previous date

Image #2 is me joining a nightmare staff (still equipped at this point)
 
Image #3 is fishy posting what time it set off (the time is an hour ahead due to timezone differences) 

Image #4 is fishy concluding that it is lost and to issue a ticket for support

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by Lajnux** [comment]
![image](https://user-images.githubusercontent.com/68188574/100525526-d9f39300-31c1-11eb-862a-26020dc0801d.png)
More info, he unequipped the item a few milli sec before the mass started. I think the food was withdrawn at same time as the unequip happend resulting in overlap of the update of the bank.

**Comment by gc** [comment]
I'm sorry this happened. This should be fixed now (as well as other similar issues people have had), due to recent changes I made.

**Comment by lostcokecan** [comment]
hello it seems this has not been fixed and the item still isnt there. I have used both "+b --search=item Harmonised nightmare staff" and "+b --search=item Harmonised orb"

**Comment by Lajnux** [comment]
try +b --search=harm
