### ISSUE TITLE
Bank search broken due to "WTF" item in text file

### ISSUE THREAD

**Issue by Bami420** [oldschoolgg/oldschoolbot#1137]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Item which used to be dial seems to have turned into a wtf item. Pls see screenshots.
I think broken item is on bank page 22, that's the page I get an error if I do =b 22 --names.
Can you please help?

thanks in advance

![9C9444AF-AE17-459A-9E78-E715AC985863](https://user-images.githubusercontent.com/71937452/103242702-88246100-4957-11eb-9c8e-1c83d4127b3a.jpeg)
![6ECCEE56-ED12-459C-8978-239BF7523AC9](https://user-images.githubusercontent.com/71937452/103242707-89558e00-4957-11eb-983f-1e4407b02a45.jpeg)

**Comment by gc** [comment]
Should be fixed now.

**Comment by Bami420** [comment]
Hey thanks for the reply, but still unable to search on BSO and WTF item is still in text file. Please see screenshots.

![DA59AA41-8B0A-43A9-8505-9224AA62A15E](https://user-images.githubusercontent.com/71937452/103281440-125ddb00-49d3-11eb-9c79-021d7c9a99a8.jpeg)
![8627F084-E147-4D5E-A28E-F41D7EC8647E](https://user-images.githubusercontent.com/71937452/103281442-138f0800-49d3-11eb-80f9-048688c35001.png)

Thanks
