### ISSUE TITLE
Lowering broad arrowtip/unf bolt prices

### ISSUE THREAD

**Issue by HouseParan73** [oldschoolgg/oldschoolbot#2030]
## 🚀 Feature Proposal

Was told to make it a github suggestion. Currently one arrowtip or unf bolt is 550 gp, 10x more than in game. And with feathers also being a high price of 50 gp each, this leads to the current gp/xp:

Broad bolts: 200 gp/xp
Broad arrows: 60 gp/xp (plus time to make headless arrows)

Both of these prices are honestly really ridiculous, 99 fletching would mean 2.6b gp with broad bolts which even for a regular account would be incredibly high but for an ironman is straight up atrocious.

**Comment by Lajnux** [comment]
fixed with ironman pricings

**Comment by LuxrayElite** [comment]
Issue partially resolved:
Feathers (Iron price lowered)

broad arrowheads (iron price lowered)

![image](https://user-images.githubusercontent.com/12814878/188465126-401f82c4-3393-4b82-9bc7-2774985b224d.png)

bolt prices weren't lowered only arrow tips
