### ISSUE TITLE
ToB doesn't send a message when the team wipes

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4197]
## 🐛 Bug Report

Title. It should return something like "@players , you wiped at Bloat!" so you can be notified+resend the trip. Right now it sends literally nothing so if you do wipe, you're most likely going to be idle for a while until realizing something is off. 
![image](https://user-images.githubusercontent.com/63373565/179569349-27cb904b-c2b6-4f58-ab84-f90eae92adfc.png)

**Comment by gc** [comment]
In the code, it definitely does send a message if you wipe, this might've be a one-off issue, if it happens again then we can re-open this and look into it.

**Comment by mylife212** [comment]
It is definitely consistent. If you search "Wipe" in #tob-duo, you can see many things from people noticing they wiped with no return message. 

This also just happened to my team - 
![image](https://user-images.githubusercontent.com/63373565/179825532-4639fb16-fccb-4cfb-a01e-32db1cd99191.png)

**Comment by gc** [comment]
Fixed in next update

**Comment by mylife212** [comment]
Unfortunately, looks like the bug is still around? Will re-open this post if it happens again.
![image](https://user-images.githubusercontent.com/63373565/181619243-a923d6e2-ff85-4f4b-80fa-65a6ac0ac19b.png)

**Comment by mylife212** [comment]
Issue is still live. Getting multiple reports of it, and got further proof. 
![image](https://user-images.githubusercontent.com/63373565/182061824-8aeb0b54-dbf6-4c82-8368-bb168988c1fe.png)
 While image may look confusing, the very top message = the trip being sent. Then theres no return trip as the fella checks time left, leading them to send a BH run
