### ISSUE TITLE
Temp CL reset not working.

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4738]
## 🐛 Bug Report

  so when I do `/tools user temp_cl reset:True` it doesn't reset it for me instead it tells me when my last reset - was. `You can view your temporary CL using, for example, `/cl name:PvM type:Temp`.
You last reset your temporary CL: <t:1651423242>`

![Screenshot_20221119_191822_Discord](https://user-images.githubusercontent.com/90441459/202878258-5493cde2-2dff-46d3-995b-a7d6e02ca7f3.png)
![SmartSelect_20221119_191832_Discord](https://user-images.githubusercontent.com/90441459/202878259-e595ecd5-bbfd-4d13-8947-51b4c0fd3ad8.jpg)

**Comment by gc** [comment]
Fixed in next update

**Comment by TURB042O** [comment]
> Fixed in next update

just letting you know this issue is still existing even after yesterday's update
