### ISSUE TITLE
Invention master cape 

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#4808]
Cape does not give 8% xp boost to invention or 3% to any other skills. "5% less materials for mastery" also gives no affect even though it shows the message.

**Comment by DarkBugz** [comment]
The 5% boost to disassemble and the 5% bonus material from disassemble do work correctly

**Comment by nwjgit** [comment]
This issue should be corrected with the merged PR above.

**Comment by DarkBugz** [comment]
5% less materials for mastery still doesnt work for any invention. This was an intended feature from testing that never got coded but all the words still show up on every trip sent. At the very least should remove the text since nothing is saved.

**Comment by DarkBugz** [comment]
![Screenshot_20221223-182602](https://github.com/oldschoolgg/oldschoolbot/assets/37970558/fc8ef9ff-972d-4f00-b7df-2ec85d3c7a7c)
![Screenshot_20221223-182532](https://github.com/oldschoolgg/oldschoolbot/assets/37970558/32137126-74e3-46e8-8817-fc52b6afd72f)
