### ISSUE TITLE
DT2 Rings are using the beta version

### ISSUE THREAD

**Issue by nwjgit** [oldschoolgg/oldschoolbot#5284]
## 🐛 Bug Report

Using the Bellator ring as an example:

This is the current ring we have in OSB/BSO: https://oldschool.runescape.wiki/w/Bellator_ring_(beta)

This is the current ring in the live game: https://oldschool.runescape.wiki/w/Bellator_ring

![Discord_w4ItNGHSCs](https://github.com/oldschoolgg/oldschoolbot/assets/69014816/4a1bda9b-63b2-4f53-9e87-d77314c59004)

This also is whats causing the rings to not be tradable: https://github.com/oldschoolgg/oldschoolbot/issues/5282#issue-1867774779

**Comment by 6enny6** [comment]
fixed in #5283

**Comment by nwjgit** [comment]
> fixed in #5283

that doesn't solve the issue of rings that have already been created.

**Comment by mylife212** [comment]
Bump.  hope this is fixed soon and not months/years from now, considering the untapped market demand for the bis rings.

**Comment by nwjgit** [comment]
Updating this here because it is in the realm of DT2 content. The Soulreaper Axe also has the same issue of using the beta ID.

Soulreaper axe in OSB/BSO: https://oldschool.runescape.wiki/w/Soulreaper_axe_(beta)

Soulreaper axe in live game: https://oldschool.runescape.wiki/w/Soulreaper_axe

**Comment by gc** [comment]
Fixed in next update
