### ISSUE TITLE
CA - Amascut's Remnant Doesn't Appear to be Completable

### ISSUE THREAD

**Issue by ColossalSeagull** [oldschoolgg/oldschoolbot#6003]
I've been trying to complete the CA - Amascut's Remnant which is just to complete a TOA of raid level 500 or higher without dying. I have done so three times and the task still does not complete. See photo showing checking task is incomplete, completing a 500 without dying (says it in message and gives cursed phalanx), and then after it is still incomplete.

![image](https://github.com/user-attachments/assets/e12b99f6-6268-4cf0-8927-49e0b9d077a9)

**Comment by DayV-git** [comment]
Many CAs are bugged right now. Should hopefully be fixed with https://github.com/oldschoolgg/oldschoolbot/pull/5981 on next bot restart

**Comment by ColossalSeagull** [comment]
![image](https://github.com/user-attachments/assets/11ce7dfc-59fe-40f0-b42b-a24552b8e93f)
Was not fixed. Did this today after newspost.
